name: CI

on: push
  
  
jobs:
  rigel:
    name: Testing ATOM with Rigel

    runs-on: ubuntu-latest

    # strategy:
    #   matrix: # the product of the entries
    #     env:
    #       - {ROS_DISTRO: noetic, ROS_REPO: main}
    # strategy:
    #   matrix: # the product of the entries
    #     env:
    #       - {ROS_DISTRO: noetic, ROS_REPO: main}
    
    # env:
    #   CCACHE_DIR: "${{ github.workspace }}/.ccache"

    steps:
      - uses: actions/checkout@v3 # clone target repo
      - run: sudo apt update && pip install poetry && git clone https://github.com/rigel-ros/rigel && cd rigel/ && poetry install
      - run: git clone https://github.com/Kazadhum/atom && ls
      # - uses: actions/cache@v2 # fetch the directory used before/after the ci run
      #   with:
      #     path: ${{ env.CCACHE_DIR }}

      #     key: ccache-${{ matrix.ROS_DISTRO }}-${{ matrix.ROS_REPO }}-${{ github.run_id }}
      #     restore-keys: |
      #       ccache-${{ matrix.ROS_DISTRO }}-${{ matrix.ROS_REPO }}-
      
      # - run: sudo apt update && sudo apt install python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool build-essential && sudo apt install python3-rosdep && sudo rosdep init && rosdep update

      # - uses: 'ros-industrial/industrial_ci@master'
      #   env: ${{matrix.env}}