name: CI

on: push
  
  
jobs:
  rigel:
    name: Testing ATOM with Rigel

    runs-on: ubuntu-latest

    strategy:
      matrix: # the product of the entries
        env:
          - {ROS_DISTRO: noetic, ROS_REPO: main}

    steps:
      
      - uses: actions/checkout@v3 # clone target repo
      - run: sudo apt update && cd ~/ && pip install git+https://github.com/rigel-ros/rigel@develop
      # && cd ~/ && git clone https://github.com/Kazadhum/atom
      # - run: cd ~/ && ls
      # - run: cd ~/rigel/ && poetry install && . /home/runner/.cache/pypoetry/virtualenvs/rigel-u4E7_ENg-py3.10/bin/activate && rigel run job dockerfile


      # - uses: actions/cache@v2 # fetch the directory used before/after the ci run
      #   with:
      #     path: ${{ env.CCACHE_DIR }}

      #     key: ccache-${{ matrix.ROS_DISTRO }}-${{ matrix.ROS_REPO }}-${{ github.run_id }}
      #     restore-keys: |
      #       ccache-${{ matrix.ROS_DISTRO }}-${{ matrix.ROS_REPO }}-
      
      # - run: sudo apt update && sudo apt install python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool build-essential && sudo apt install python3-rosdep && sudo rosdep init && rosdep update
      # - run: sudo apt update && sudo apt install qtbase5-dev qtdeclarative5-dev
      # - uses: 'ros-industrial/industrial_ci@master'
      #   env: ${{matrix.env}}