name: Paralel CI Test

on: push
  
  
jobs:
  rigel:
    name: Testing ATOM with Rigel

    runs-on: ubuntu-latest

    strategy:
      matrix: # the product of the entries
        number: [1, 2]

    steps:

      - uses: actions/setup-node@v3
        with: 
          folder_number: ${{ matrix.number }}

      # - name: DEBUG STEP - Check Directory Structure
      #   run: cd $HOME && mkdir $NUMBER && ls -a
      #   with:
      #     env:
      #       NUMBER: ${{ matrix.number }}

      # - name: DEBUG STEP - Check Directory Structure 2
      #   run: cd $HOME/.rigel/ && ls -a

      # - name: DEBUG STEP - Check Directory Structure 3
      #   run: cd $HOME/.rigel/archives/ && tree
