name: Paralel CI Test

on: push
  
  
jobs:
  rigel:
    name: Testing ATOM with Rigel

    runs-on: ubuntu-latest

    strategy:
      matrix: # the product of the entries
        number: [1, 2]

    steps:
      
      - uses: actions/checkout@v3 # clone target repo
      
      - name: Install Rigel and clone ATOM repo
        run: sudo apt update && sudo apt install tree && cd ~/ && pip install git+https://github.com/rigel-ros/rigel@develop && cd ~/ && git clone https://github.com/Kazadhum/atom
      
      - name: Install my File Introspection Plugin
        run: pip install git+https://github.com/Kazadhum/file_intro_plugin

      - name: Move corresponding Rigelfile
        run: cd ~/atom/rigelfiles && mv Rigelfile_$RIGELFILE_NUMBER ../Rigelfile  
        env:
          RIGELFILE_NUMBER: ${{ matrix.number }}

      # TESTING TO FIX CALIBRATION ISSUE
      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      # - name: Start Xvfb
      #   run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      
      # - name: Set display variable
      #   run: export DISPLAY=:99

  ##################################################################################

      - name: DEBUG STEP - Check Directory Structure
        run: cd $HOME/atom && ls -a && cd rigelfiles/ && ls -a

      # - name: Build ATOM image using Rigel
      #   run: cd ~/atom/ && rigel run sequence deploy
      #   env:
      #     DISPLAY: :0

      - name: DEBUG STEP - Get Docker info
        run: docker info

      - name: Run ATOM calibration and evaluation using Rigel DEBUG
        uses: GabrielBB/xvfb-action@v1
        with:  
          run: cd /home/runner && ls
          # env:
            # DISPLAY: :99

#      - name: DEBUG STEP - Check Directory Structure 2
#        run: cd $HOME/.rigel/ && ls -a

#      - name: DEBUG STEP - Check Directory Structure 3
#        run: cd $HOME/.rigel/archives/ && tree

      - name: DEBUG STEP - Check Parallel Job Var
        run: echo $NUMBER
        env:
          NUMBER: ${{ matrix.number }}
      # - uses: actions/cache@v2 # fetch the directory used before/after the ci run
      #   with:
      #     path: ${{ env.CCACHE_DIR }}

      #     key: ccache-${{ matrix.ROS_DISTRO }}-${{ matrix.ROS_REPO }}-${{ github.run_id }}
      #     restore-keys: |
      #       ccache-${{ matrix.ROS_DISTRO }}-${{ matrix.ROS_REPO }}-
      
      # - run: sudo apt update && sudo apt install python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool build-essential && sudo apt install python3-rosdep && sudo rosdep init && rosdep update
      # - run: sudo apt update && sudo apt install qtbase5-dev qtdeclarative5-dev
      # - uses: 'ros-industrial/industrial_ci@master'
      #   env: ${{matrix.env}}
